---
- name: programPlaybook
  hosts:
    - local
  become: False
  gather_facts: True
  vars:
    host: "{{ ansible_hostname | upper }}"
  tasks:
    - name: Prepare host
      package: 
        name: 
          - docker-ce
    - name: Create a program container
      docker_container:
        name: programContainer
        image: marcodominguez/diplomatura2022s1:10
        state: started
        recreate: yes
        restart: yes
      register: command_output
    - debug:
        var: command_output
